### ISSUE TITLE
Feature Request: add support for namespacePath in addition to migrationPath

### ISSUE THREAD

**Issue by thyseus** [iRipVanWinkle/codeception-migration#2]
Since Yii 2.0.10 you cann add a 'namespacePath' to your console configuration:

http://www.yiiframework.com/doc-2.0/guide-db-migrations.html#namespaced-migrations

The official yii2-queue extensions uses this: 

https://github.com/yiisoft/yii2-queue/blob/master/docs/guide/driver-db.md#db-driver

It would be /awesome/ if this extension could be improved to use the new 'namespacePath' feature in addition to the 'migrationPath'. 

It would be /even more awesome/ if the extensions could be improved to also read the web/console.php configuration so i do not need to configure everything twice.

Thanks a lot !

**Comment by iRipVanWinkle** [comment]
completed

**Comment by thyseus** [comment]
Kewl ! Thanks a lot ! I will use this feature in my system.
